### ISSUE TITLE
python3 运行后报gbk编码错误

### ISSUE THREAD

**Issue by sunchenguang** [MrQianJinSi/poetry_analyzer#3]
运行第一个程序`word_level_analyzer.py`时，报下面的错误，设置`encoding='gb18030'`后就报`gb18030`编码错误。求解该编解码错误

```
E:\github\poetry_analyzer-master>python word_level_analyzer.py
D:\Anaconda3Work\lib\site-packages\gensim\utils.py:855: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
Model loaded succeed
Traceback (most recent call last):
  File "word_level_analyzer.py", line 164, in <module>
    main()
  File "word_level_analyzer.py", line 157, in main
    char_counter, author_counter, genre_counter = cut_qts_to_words(args.qts_path, args.words_path)
  File "word_level_analyzer.py", line 33, in cut_qts_to_words
    for line in f:
UnicodeDecodeError: 'gb18030' codec can't decode byte 0x96 in position 18: illegal multibyte sequence

```

**Comment by MrQianjinsi** [comment]
确实有这个问题，不同操作系统的默认编码不同。我已经更新了代码以解决这个问题，请再试一下最新版。

**Comment by sunchenguang** [comment]
- 可以了。但是还需要手动将txt文件改为utf-8编码。
- 另外程序执行太慢，40000多条记录，要好几十分钟根本等不了，考虑优化或者减少数据量。
- 可以把写死的文件路径抽出来作为配置文件，便于随时修改。
- 最好来个简体字版本，繁体字看着难受

辛苦PO主，同三体粉

**Comment by MrQianjinsi** [comment]
谢谢你的建议。
1.主要是分词太耗时间，应该有很大优化空间，我后面有时间再看看THULAC的源码。
2. 暂时还没想弄配置文件，我觉得现在的功能很简单，还没有弄个配置文件的必要。等后面复杂度高了我再改。
3.CBDB里面的所有汉字都是繁体，我使用繁体也没什么障碍。如果真的想用简体，可以用[OpenCC](https://github.com/BYVoid/OpenCC)来转换。
